### ISSUE TITLE
Provide installation guidance for HTTP add-on

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/external-scalers#11]
Provide installation guidance for HTTP add-on by providing the `install` section as per https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml#L31

This should help them install the external scaler.

Example: https://artifacthub.io/packages/keptn/keptn-integrations/dynatrace-service?modal=install ([source](https://github.com/keptn-sandbox/artifacthub/blob/main/dynatrace/0.17.0/artifacthub-pkg.yml))

**Comment by tomkerkhove** [comment]
@arschles Would you mind picking this up before shipping v0.2 please? I can help on this if you prefer.

**Comment by arschles** [comment]
@tomkerkhove yep, indeed I can. I'll pair this with the docs on the website (https://github.com/kedacore/keda-docs/pull/554)

**Comment by tomkerkhove** [comment]
Sure,thanks!

But just to be clear, this needs to be part of the Artifact Hub configuration in this repo.

**Comment by arschles** [comment]
yup, I understand. I'm preparing a draft PR to push up to this repo
